name: ${project.name}
version: ${project.version}
description: ${project.description}

author: Ullarah

main: ${project.groupId}.${project.artifactId}.PostalInit

commands:
  postal:
    description: Main Postal Commands.
    usage: |
      <command> help : Shows help to player.
      <command> blacklist <player> : Blacklists the players inbox.
      <command> modify <player> : View the players inbox.
      <command> clear <player> : Clears the players inbox.
      <command> reset <player> : Resets busy status of inbox.
  post:
    description: Inbox of other Player
    usage: |
      <command> <player> : Opens up players inbox to post items.
  inbox:
    description: Owners Inbox
    usage: |
      <command> : Views your own inbox.
      <command> upgrade : Upgrades your inbox.

permissions:
  postal.staff:
    description: Grant all of the staff commands
    children:
      postal.blacklist: true
      postal.modify: true
      postal.clear: true
      postal.reset: true